### ISSUE TITLE
SSO API 파라미터 변경 필요

### ISSUE THREAD

**Issue by KTCloud-git** [KTCloud-git/bizstore#2]
변경내용: 용량, 개수 옵션 추가

**Comment by KTCloud-git** [comment]
추가할 내용 상세 정의

추가할 옵션1. 
요금항목: 공용 용량 nGB m개
일회성여부: X
과금주기: 월
단가: 

추가할 옵션2.
요금항목: 전자메일 용량 nGB m개
일회성여부: X
과금주기: 월
단가:

**Comment by YongwoonJang** [comment]
관련 작업 종료로 이슈 정리.
