### ISSUE TITLE
BizOffice) cust_id 이외 관리자 id 값 확인

### ISSUE THREAD

**Issue by JunghwanSeo** [KTCloud-git/bizstore#4]
cust_id( user-id-for-kaoni )이 외 관리자 id 추가 요청이 있었는데,
biz office api 문서에서는 관리자 id 정보를 확인할 수 없습니다.

어떤 값을 사용하면 되는지 api로 제공받아야 한다면 문서 업데이트가 필요합니다.

**Comment by YongwoonJang** [comment]
안녕하세요. user-id-for-kaoni 가 관리자 ID 입니다. 이외 CUST_ID 는 EPC 로 시작하는 값입니다. 
단, MIgration에 따라서 이관받은 고객의 CUST_ID는 EPC가 아니라 user-id-for-kaoni와 동일하니 참고하세요.
